events {}

http {
    server {
        listen 80;

        location / {
            # This forwards traffic to your backend container
            proxy_pass http://fete-store-backend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}